### ISSUE TITLE
What is the biggest difference between relevance matching and semantic matching?

### ISSUE THREAD

**Issue by guotong1988** [jinfengr/hcan#2]
I have read the paper, But still confuse about it.
From my view, I think exact match signal is the biggest difference.
Question-question pair have more exact match words than question-answer pair.
@jinfengr Thank you!

**Comment by jinfengr** [comment]
The RM module is designed to be asymmetric, where the matching signals are generated and aggregated for only query phrases (as query is more concise and contains less noise). On the other hand, SM is symmetric so that we could capture bi-directional matching signals. Another big difference is that RM aims to capture keyword-based matching signals, while SM is to capture query-aware document representations and document-aware query representations (a compare and BiLSTM to aggregate the representation signals). Both RM and SMs are designed to behave similar to the best practice in neural IR and NLP settings.
